//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB.Shop_Management.Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells_Details
    {
        public int Sellsid { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public double Qnty { get; set; }
        public string Unit { get; set; }
        public decimal Total { get; set; }
    
        public virtual Sell Sell { get; set; }
    }
}
