//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB.Shop_Management.Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public Sell()
        {
            this.Sells_Details = new HashSet<Sells_Details>();
        }
    
        public int SellsId { get; set; }
        public string CustomerId { get; set; }
        public string SellsDate { get; set; }
        public string TotalPrice { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Sells_Details> Sells_Details { get; set; }
    }
}
